dist: trusty
sudo: false
git:
  depth: false
env:
  global:
  - CC_TEST_REPORTER_ID=53eef44d00d3465aeaf806ea310cfc5497e7473d13ae05fbc753890c39712c60
  - secure: LUP1UxwneWYdOPQWWxmL7/nN34N+Iu9I+nf4dcbX230KCoHvEFpUpAEegZMX0eOwamMZTeIAiMH+5NzMz9Z4wvxy8bAMnS3CfvtZxh8Mb4xQlEZU/M4cLKTtUeh3LQC8qSlUHhIEEqiPbed2GTYsMLDm5XX34/d0f588cwZQIlQ5eoBC3nZGihwwCEj87LIOzMZYwxCl5VcWAQ5lnogu3qSVLSlDIbowwi35QG5tY/P0SYQV9zEmSVAdks6QWTydi9RQMthNCwJbYIyDXERPBlRIK/mVMIYYb6ysswh4hbRL3d5YrgtSPaUr44kvETxLuJlfnNzBxYRsITTfxl3WsUaNIINaFTC1lhfYxLUNZI5ySh5fB+mhOBcYe2/UyoQo08geAkDUGOis6VWP05Kizy0bpMel29PxUBn5q1lQRDMMg5T1k8l37i/E13uZLSprjh/UoVM2wG4k3MmVSBndsg4S/B/gjKnQ6/8rBFc14JDNYqlkpkBa4ONE/y/9N7EusDoQ74scufRkS5p4E1y+LAhLaAFk4F7BuKfjRhqh2eB6odI7vn9l4rs/mQ+3sMTtdiROT0+MMxzvgvyGz43eROUUfe1wEXgPekGJl9wIaG5SohVGFLBU8VKhIbM9e0hxx/1QWHIuJvMWLcBdfSc5CA7RBCDYLRDIhwrC8x/6h5Q=
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: VnnKfLIe2plQb/WPXk3tgMrcA7GrJG+l6uUNt33pwzeRBgZi8ZX1CQRDsCjioZVcO7c7ILIyQmDr9pAx+wKcvTScd0DC77KWxGm5P/TS0W+v9wDgGCcI9tGYfcV0VuS/X/FO8u07gKBw8V5Y+oEMxBkPGVErhcoY/62rJyB4IWMyL2Q9u1miAvAbOFZSvpPDJr/lHM+EYgXFY9jqZ61CA0MfPPlVWfgcNG0wsAhxAwIDxiAOpzWjm0Z0PbaKoOhs0HGNnGK+apB97K9hkMIOnFXsC6NKrE9W/NMakftW1NaVLDjEGkHxUceCMz3foXTI2wvWdMrsB90nhAl4cR16wjxrU/OI9Zem8V/lFY0MZz3rwIedz35eWvmG8wAEwQ35cfLnqR0PvIEiZh16ggd8sHDD0BPmOKBsRhcTKw4EWhT7CNWxkWOrVY4PFrgK/22oE2GuBSn1eK/wgjhw5UGQgdseGk4HpZODlTBXmIig6OAGDSjdta//Ck6nQaNjyXGiETrWtHJNSA+pQEYQz0ruqOTSExaWRDnMj5hm8PP8xbxTRIYLldEshr8pLIgxS4m/PP0oEs6lMXdrYF+YZ7+rl+hJ0cDiIP2sKyaL+bmhwtpgtGH/ZbFGX3bE3sJTgajwouqLv9wKMJTr0t/4A/4u7itHo9IutGJHAmChphgUhHw=AoOl+89E3Of2StjwwGRGMCrh0mlKJd0Y3IhV15PY3t2OoPRKKbHaEFFUTLIXD2a9z2hWv+BasH9jz6+xlosgTdV6OfS6Es0yLAHXn/qlyQyu34Fmzw64/Tj1iVbIMIhCfbIgARh+JpbI3rfjCzlmMQW1ffY0iHo6draJFFu6sAJmdhr4qgBandiiCIXzKUvz3hj16GCiM/tf9yhxipW3+dNvMSYzF/OIwLu8rEYJXAlLfp8J4iz4w4nnDo8Iuk0UCkceKgfX8BLYnpOiH5DppMu9VhUfa9/e4xskd0fD7RxbAptCYWKHnVjNSxmvlDJT3v+puxKQDTzMCgTHmaEpxl4a0tWOjUMr/A0Y1v7CxPSt9NwThDarL6xf+dTmIV5a1f7+6OycNAAahR5n4UPq461rg+etVRVaZqqQ5h4g+NZEeNn7pEOl8fR10LRC2/3BYkEewaHDKblzrdpbfJX3I1niwRxden7qknNOdRYtwL7hXll1m2Sy0XV3PZZIArbfDcgZU6SyAnYJLEvyZeWPhlvnlJFV1379vK80YT7gQyH3h5uAxdBcYkFYvsx7Q+IUcE1fwrfaICLnNQqLlGjmNd+5YjftCzJVmF+h2HR31GyHsMQkuhwLjyLeQ/fblaYVLMoIbsIo5sLeqsW7S9FIXjd7Of9YTWutAim2y7aMNII=
language: python
python:
- '3.6'
before_install:
- pip install --upgrade pytest
- pip install tensorflow
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=silence_tensorflow --cov-report xml:coverage.xml
- coverage report
- coverage xml
- sonar-scanner
after_success:
- coveralls
notifications:
  email: false
